version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    container_name: genomeguard-api-minimal
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      - ENVIRONMENT=production
    volumes:
      - ./data:/app/data
      - ./models:/app/models

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: genomeguard-web-minimal
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8000
    depends_on:
      - api

networks:
  default:
    driver: bridge